name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Uncomment if needed
      # - run: yarn dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --immutable
      - uses: nrwl/nx-set-shas@v4

      # Show affected projects for easier debugging and monitoring
      - name: Show Affected Projects
        run: |
          echo "Fetching affected projects..."
          yarn nx show projects --affected

      # Run lint, test, and build for affected projects
      - name: Lint, Test, and Build Affected Projects
        run: |
          yarn nx affected --targets=lint,test,build --verbose

      # Deploy affected projects only if previous steps succeed
      - name: Deploy Affected Projects
        if: success()
        env:
          DEPLOY_TOKEN_VUE_APP_1: ${{ secrets.DEPLOY_TOKEN_VUE_APP_1 }}
          DEPLOY_TOKEN_VUE_APP_2: ${{ secrets.DEPLOY_TOKEN_VUE_APP_2 }}
        run: |
          yarn nx affected --targets=deploy --verbose
