name: CI with Pnpm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install required Deno version
      - uses: denoland/setup-deno@v2
        with:
          deno-version: 2.1.4

      # Cache Deno dependencies
      - name: Cache Deno Dependencies
        uses: actions/cache@v4
        env:
          DENO_DIR: ~/.cache/deno
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json', '**/deno.lock') }}

      # Install pnpm using pnpm/action-setup
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      # Set up Node.js with caching for pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Install dependencies with pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Set NX_BASE and NX_HEAD dynamically using nrwl/nx-set-shas
      - name: Set NX_BASE and NX_HEAD for nx affected commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'main'

      - run: |
          echo "NX_BASE=${{ env.NX_BASE }}"
          echo "NX_HEAD=${{ env.NX_HEAD }}"

      # Debugging and monitoring affected projects
      - name: Show Affected Projects
        run: |
          pnpm nx show projects --affected

      # Lint, Test, and Build affected projects
      - name: Lint, Test, and Build Affected Projects
        run: |
          pnpm nx affected --targets=lint,test,build,fmt --verbose

      # Install Azure Static Web Apps CLI
      - name: Install SWA CLI
        run: |
          npm install -g @azure/static-web-apps-cli

      # Pre-download StaticSitesClient binary, this will always fail but won't affect further steps.
      - name: Dry running to ensure StaticSitesClient binary is downloaded before actual deployment triggers to avoid failures
        run: |
          swa deploy --dry-run --deployment-token=${{ secrets.DEPLOY_TOKEN_VUE_APP_1 }} || true

      # Deploy affected projects only if previous steps succeed
      - name: Deploy Affected Projects
        if: success()
        env:
          DEPLOY_TOKEN_VUE_APP_1: ${{ secrets.DEPLOY_TOKEN_VUE_APP_1 }}
          DEPLOY_TOKEN_VUE_APP_2: ${{ secrets.DEPLOY_TOKEN_VUE_APP_2 }}
        run: |
          pnpm nx affected --targets=deploy --verbose
